<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\BeautyOfNumbers.Core\BeautyOfNumbers.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="OxyPlot.SkiaSharp" />
  </ItemGroup>

</Project>
