<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\BeautyOfNumbers.Core\BeautyOfNumbers.Core.csproj" />
    <ProjectReference Include="..\BeautyOfNumbers.Rendering\BeautyOfNumbers.Rendering.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Extended.Wpf.Toolkit" />
    <PackageReference Include="SkiaSharp.Views.WPF" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="**\*.xaml.cs">
      <DependentUpon>%(Filename)</DependentUpon>
    </Compile>
  </ItemGroup>

</Project>
